# Generated by Django 4.2.4 on 2026-04-25 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.IntegerField()),
                ('prospeccao', models.IntegerField(null=True)),
                ('etapa', models.CharField(max_length=25)),
                ('data_ocorrencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocorrencia', models.CharField(max_length=25)),
                ('informacoes', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
