# Generated by Django 4.2.4 on 2026-04-25 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospeccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_negocio', models.CharField(max_length=255)),
                ('segmento', models.CharField(max_length=255)),
                ('servicos_produtos', models.CharField(max_length=255)),
                ('participacao_comercial', models.CharField(max_length=255)),
                ('participacao_efetiva', models.CharField(max_length=255)),
                ('consultor', models.CharField(max_length=255)),
                ('comissao', models.BooleanField(null=True)),
                ('data_inicio_prospeccao', models.DateField()),
                ('data_contato_inicial', models.DateField()),
                ('data_proxima_acao', models.DateField()),
                ('preferencia_contato', models.CharField(max_length=255)),
                ('horario_contato', models.CharField(max_length=255)),
                ('observacao', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('versao', models.IntegerField()),
                ('lead', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
            ],
        ),
    ]
