# Generated by Django 4.2.4 on 2026-04-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nomeEmpresa', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('origem', models.CharField(max_length=500)),
                ('cargo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=500)),
                ('data_cadastro', models.DateField()),
                ('data_ultima_alteracao', models.DateField()),
            ],
        ),
    ]
