# Generated by Django 4.2.4 on 2026-04-25 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fechamento', models.DateField()),
                ('status_proposta', models.CharField(max_length=255)),
                ('motivo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_proposta', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField()),
                ('desc_proposta', models.CharField()),
                ('tipo_projeto', models.CharField(max_length=255)),
                ('influenciador_decisor', models.CharField(max_length=255)),
                ('perfil_orcamento', models.CharField(max_length=255)),
                ('prob_fechamento', models.CharField(max_length=255)),
                ('status_proposta', models.CharField(max_length=255)),
                ('valor_proposta', models.FloatField()),
                ('material_insumo', models.CharField(max_length=500)),
                ('servicos', models.CharField()),
                ('somatorio', models.FloatField()),
                ('tipo_contato', models.CharField()),
                ('versao', models.CharField()),
                ('ativa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fechamento', models.DateField()),
                ('status_proposta', models.CharField(max_length=255)),
                ('valor_proposta', models.FloatField()),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proposta.proposta')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField()),
                ('hora_cadastrado', models.TimeField()),
                ('membro_equipe', models.CharField(max_length=100)),
                ('nome_negocio', models.CharField(max_length=100)),
                ('responsavel_negocio', models.CharField(max_length=100)),
                ('concluida', models.BooleanField()),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proposta.proposta')),
            ],
        ),
    ]
