# Generated by Django 4.2.4 on 2026-04-25 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospeccao', '0001_initial'),
        ('proposta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='consultor_prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposta',
            name='prospeccao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='prospeccao.prospeccao'),
        ),
        migrations.AddField(
            model_name='perdido',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proposta.proposta'),
        ),
    ]
